version: '3'
services:
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=smaug
  web:
    image: '${IMAGE:-docker-ux.dbc.dk/smaug-master:latest}'
    env_file: ./test/test.env
    environment:
      - DATABASE_URI=postgres://smaug@database/smaug
      - BABEL_CACHE_PATH=~/app/babel.cache.json
    depends_on:
      - database
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; npm run migrate; npm run start'
  e2e:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker.dbc.dk/cypress:latest
    volumes:
      - './e2e:/app/e2e'
    depends_on:
      - web
    environment:
      - CYPRESS_adminUrl=http://web:3002
      - CYPRESS_oAuthUrl=http://web:3001
      - CYPRESS_configUrl=http://web:3003
      - CYPRESS_baseUrl=http://web:3001

    command: bash -c 'npm run cy'
