version: '3'
services:
  redis:
    image: redis:5.0.6
# see comment below about redis
  database:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=smaug
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    image: '${IMAGE:-docker-fbiscrum.artifacts.dbccloud.dk/smaug-master:latest}'
    env_file: ./test/test.env
    environment:
      - DATABASE_URI=postgres://smaug@database/smaug
# the redis above is not at cluster, so the setting from the env_file is used
# when/if a dbc redis cluster image is made, this setting should be included again
#      - REDIS_CLUSTER=redis
    depends_on:
      - database
      - redis
    command: bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; npm run start'
  e2e:
    ipc: host ## Prevent Docker Crash in Cypress (https://github.com/cypress-io/cypress/issues/350)
    image: docker-dbc.artifacts.dbccloud.dk/cypress:old-202228
    volumes:
      - './e2e:/app/e2e'
    depends_on:
      - web
    environment:
      - CYPRESS_adminUrl=http://web:3002
      - CYPRESS_oAuthUrl=http://web:3001
      - CYPRESS_configUrl=http://web:3003
      - CYPRESS_baseUrl=http://web:3001

    command: bash -c 'npm run cy'
